"""Add new column in resume table

Revision ID: 1a20fd8294b7
Revises: 6e18a5ffc1fb
Create Date: 2026-06-24 16:32:14.939921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a20fd8294b7'
down_revision = '6e18a5ffc1fb'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'analysis_status',
                sa.String(length=20),
                nullable=False,
                server_default='pending'
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('analysis_status')

    # ### end Alembic commands ###
