"""create audit logs

Revision ID: 26a9cde2c82f
Revises: 78c043cc4ef6
Create Date: 2026-06-03 16:20:24.977240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a9cde2c82f'
down_revision = '78c043cc4ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.alter_column('is_analyzed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.alter_column('is_analyzed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
