"""added ai analysis caching

Revision ID: ed7f71c5c52f
Revises: eadbca482d66
Create Date: 2026-05-26 16:18:27.088301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7f71c5c52f'
down_revision = 'eadbca482d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ats_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_analyzed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('analyzed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ai_model', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('ai_model')
        batch_op.drop_column('analyzed_at')
        batch_op.drop_column('is_analyzed')
        batch_op.drop_column('ats_score')
        batch_op.drop_column('ai_feedback')

    # ### end Alembic commands ###
